export const timezones = [
  { value: "Africa/Abidjan", label: "Africa/Abidjan" },
  { value: "Africa/Algiers", label: "Africa/Algiers" },
  { value: "Africa/Bissau", label: "Africa/Bissau" },
  { value: "Africa/Cairo", label: "Africa/Cairo" },
  { value: "Africa/Casablanca", label: "Africa/Casablanca" },
  { value: "Africa/Ceuta", label: "Africa/Ceuta" },
  { value: "Africa/El_Aaiun", label: "Africa/El_Aaiun" },
  { value: "Africa/Johannesburg", label: "Africa/Johannesburg" },
  { value: "Africa/Juba", label: "Africa/Juba" },
  { value: "Africa/Khartoum", label: "Africa/Khartoum" },
  { value: "Africa/Lagos", label: "Africa/Lagos" },
  { value: "Africa/Maputo", label: "Africa/Maputo" },
  { value: "Africa/Monrovia", label: "Africa/Monrovia" },
  { value: "Africa/Nairobi", label: "Africa/Nairobi" },
  { value: "Africa/Ndjamena", label: "Africa/Ndjamena" },
  { value: "Africa/Sao_Tome", label: "Africa/Sao_Tome" },
  { value: "Africa/Tripoli", label: "Africa/Tripoli" },
  { value: "Africa/Tunis", label: "Africa/Tunis" },
  { value: "Africa/Windhoek", label: "Africa/Windhoek" },
  { value: "America/Adak", label: "America/Adak" },
  { value: "America/Anchorage", label: "America/Anchorage" },
  { value: "America/Araguaina", label: "America/Araguaina" },
  {
    value: "America/Argentina/Buenos_Aires",
    label: "America/Argentina/Buenos_Aires",
  },
  {
    value: "America/Argentina/Catamarca",
    label: "America/Argentina/Catamarca",
  },
  { value: "America/Argentina/Cordoba", label: "America/Argentina/Cordoba" },
  { value: "America/Argentina/Jujuy", label: "America/Argentina/Jujuy" },
  { value: "America/Argentina/La_Rioja", label: "America/Argentina/La_Rioja" },
  { value: "America/Argentina/Mendoza", label: "America/Argentina/Mendoza" },
  {
    value: "America/Argentina/Rio_Gallegos",
    label: "America/Argentina/Rio_Gallegos",
  },
  { value: "America/Argentina/Salta", label: "America/Argentina/Salta" },
  { value: "America/Argentina/San_Juan", label: "America/Argentina/San_Juan" },
  { value: "America/Argentina/San_Luis", label: "America/Argentina/San_Luis" },
  { value: "America/Argentina/Tucuman", label: "America/Argentina/Tucuman" },
  { value: "America/Argentina/Ushuaia", label: "America/Argentina/Ushuaia" },
  { value: "America/Asuncion", label: "America/Asuncion" },
  { value: "America/Bahia", label: "America/Bahia" },
  { value: "America/Bahia_Banderas", label: "America/Bahia_Banderas" },
  { value: "America/Barbados", label: "America/Barbados" },
  { value: "America/Belem", label: "America/Belem" },
  { value: "America/Belize", label: "America/Belize" },
  { value: "America/Boa_Vista", label: "America/Boa_Vista" },
  { value: "America/Bogota", label: "America/Bogota" },
  { value: "America/Boise", label: "America/Boise" },
  { value: "America/Cambridge_Bay", label: "America/Cambridge_Bay" },
  { value: "America/Campo_Grande", label: "America/Campo_Grande" },
  { value: "America/Cancun", label: "America/Cancun" },
  { value: "America/Caracas", label: "America/Caracas" },
  { value: "America/Cayenne", label: "America/Cayenne" },
  { value: "America/Chicago", label: "America/Chicago" },
  { value: "America/Chihuahua", label: "America/Chihuahua" },
  { value: "America/Ciudad_Juarez", label: "America/Ciudad_Juarez" },
  { value: "America/Costa_Rica", label: "America/Costa_Rica" },
  { value: "America/Cuiaba", label: "America/Cuiaba" },
  { value: "America/Danmarkshavn", label: "America/Danmarkshavn" },
  { value: "America/Dawson", label: "America/Dawson" },
  { value: "America/Dawson_Creek", label: "America/Dawson_Creek" },
  { value: "America/Denver", label: "America/Denver" },
  { value: "America/Detroit", label: "America/Detroit" },
  { value: "America/Edmonton", label: "America/Edmonton" },
  { value: "America/Eirunepe", label: "America/Eirunepe" },
  { value: "America/El_Salvador", label: "America/El_Salvador" },
  { value: "America/Fort_Nelson", label: "America/Fort_Nelson" },
  { value: "America/Fortaleza", label: "America/Fortaleza" },
  { value: "America/Glace_Bay", label: "America/Glace_Bay" },
  { value: "America/Goose_Bay", label: "America/Goose_Bay" },
  { value: "America/Grand_Turk", label: "America/Grand_Turk" },
  { value: "America/Guatemala", label: "America/Guatemala" },
  { value: "America/Guayaquil", label: "America/Guayaquil" },
  { value: "America/Guyana", label: "America/Guyana" },
  { value: "America/Halifax", label: "America/Halifax" },
  { value: "America/Havana", label: "America/Havana" },
  { value: "America/Hermosillo", label: "America/Hermosillo" },
  {
    value: "America/Indiana/Indianapolis",
    label: "America/Indiana/Indianapolis",
  },
  { value: "America/Indiana/Knox", label: "America/Indiana/Knox" },
  { value: "America/Indiana/Marengo", label: "America/Indiana/Marengo" },
  { value: "America/Indiana/Petersburg", label: "America/Indiana/Petersburg" },
  { value: "America/Indiana/Tell_City", label: "America/Indiana/Tell_City" },
  { value: "America/Indiana/Vevay", label: "America/Indiana/Vevay" },
  { value: "America/Indiana/Vincennes", label: "America/Indiana/Vincennes" },
  { value: "America/Indiana/Winamac", label: "America/Indiana/Winamac" },
  { value: "America/Inuvik", label: "America/Inuvik" },
  { value: "America/Iqaluit", label: "America/Iqaluit" },
  { value: "America/Jamaica", label: "America/Jamaica" },
  { value: "America/Juneau", label: "America/Juneau" },
  {
    value: "America/Kentucky/Louisville",
    label: "America/Kentucky/Louisville",
  },
  {
    value: "America/Kentucky/Monticello",
    label: "America/Kentucky/Monticello",
  },
  { value: "America/La_Paz", label: "America/La_Paz" },
  { value: "America/Lima", label: "America/Lima" },
  { value: "America/Los_Angeles", label: "America/Los_Angeles" },
  { value: "America/Maceio", label: "America/Maceio" },
  { value: "America/Managua", label: "America/Managua" },
  { value: "America/Manaus", label: "America/Manaus" },
  { value: "America/Martinique", label: "America/Martinique" },
  { value: "America/Matamoros", label: "America/Matamoros" },
  { value: "America/Mazatlan", label: "America/Mazatlan" },
  { value: "America/Menominee", label: "America/Menominee" },
  { value: "America/Merida", label: "America/Merida" },
  { value: "America/Metlakatla", label: "America/Metlakatla" },
  { value: "America/Mexico_City", label: "America/Mexico_City" },
  { value: "America/Miquelon", label: "America/Miquelon" },
  { value: "America/Moncton", label: "America/Moncton" },
  { value: "America/Monterrey", label: "America/Monterrey" },
  { value: "America/Montevideo", label: "America/Montevideo" },
  { value: "America/New_York", label: "America/New_York" },
  { value: "America/Nome", label: "America/Nome" },
  { value: "America/Noronha", label: "America/Noronha" },
  {
    value: "America/North_Dakota/Beulah",
    label: "America/North_Dakota/Beulah",
  },
  {
    value: "America/North_Dakota/Center",
    label: "America/North_Dakota/Center",
  },
  {
    value: "America/North_Dakota/New_Salem",
    label: "America/North_Dakota/New_Salem",
  },
  { value: "America/Nuuk", label: "America/Nuuk" },
  { value: "America/Ojinaga", label: "America/Ojinaga" },
  { value: "America/Panama", label: "America/Panama" },
  { value: "America/Paramaribo", label: "America/Paramaribo" },
  { value: "America/Phoenix", label: "America/Phoenix" },
  { value: "America/Port-au-Prince", label: "America/Port-au-Prince" },
  { value: "America/Porto_Velho", label: "America/Porto_Velho" },
  { value: "America/Puerto_Rico", label: "America/Puerto_Rico" },
  { value: "America/Punta_Arenas", label: "America/Punta_Arenas" },
  { value: "America/Rankin_Inlet", label: "America/Rankin_Inlet" },
  { value: "America/Recife", label: "America/Recife" },
  { value: "America/Regina", label: "America/Regina" },
  { value: "America/Resolute", label: "America/Resolute" },
  { value: "America/Rio_Branco", label: "America/Rio_Branco" },
  { value: "America/Santarem", label: "America/Santarem" },
  { value: "America/Santiago", label: "America/Santiago" },
  { value: "America/Santo_Domingo", label: "America/Santo_Domingo" },
  { value: "America/Sao_Paulo", label: "America/Sao_Paulo" },
  { value: "America/Scoresbysund", label: "America/Scoresbysund" },
  { value: "America/Sitka", label: "America/Sitka" },
  { value: "America/St_Johns", label: "America/St_Johns" },
  { value: "America/Swift_Current", label: "America/Swift_Current" },
  { value: "America/Tegucigalpa", label: "America/Tegucigalpa" },
  { value: "America/Thule", label: "America/Thule" },
  { value: "America/Tijuana", label: "America/Tijuana" },
  { value: "America/Toronto", label: "America/Toronto" },
  { value: "America/Vancouver", label: "America/Vancouver" },
  { value: "America/Whitehorse", label: "America/Whitehorse" },
  { value: "America/Winnipeg", label: "America/Winnipeg" },
  { value: "America/Yakutat", label: "America/Yakutat" },
  { value: "Antarctica/Casey", label: "Antarctica/Casey" },
  { value: "Antarctica/Davis", label: "Antarctica/Davis" },
  { value: "Antarctica/Macquarie", label: "Antarctica/Macquarie" },
  { value: "Antarctica/Mawson", label: "Antarctica/Mawson" },
  { value: "Antarctica/Palmer", label: "Antarctica/Palmer" },
  { value: "Antarctica/Rothera", label: "Antarctica/Rothera" },
  { value: "Antarctica/Troll", label: "Antarctica/Troll" },
  { value: "Asia/Almaty", label: "Asia/Almaty" },
  { value: "Asia/Amman", label: "Asia/Amman" },
  { value: "Asia/Anadyr", label: "Asia/Anadyr" },
  { value: "Asia/Aqtau", label: "Asia/Aqtau" },
  { value: "Asia/Aqtobe", label: "Asia/Aqtobe" },
  { value: "Asia/Ashgabat", label: "Asia/Ashgabat" },
  { value: "Asia/Atyrau", label: "Asia/Atyrau" },
  { value: "Asia/Baghdad", label: "Asia/Baghdad" },
  { value: "Asia/Baku", label: "Asia/Baku" },
  { value: "Asia/Bangkok", label: "Asia/Bangkok" },
  { value: "Asia/Barnaul", label: "Asia/Barnaul" },
  { value: "Asia/Beirut", label: "Asia/Beirut" },
  { value: "Asia/Bishkek", label: "Asia/Bishkek" },
  { value: "Asia/Chita", label: "Asia/Chita" },
  { value: "Asia/Choibalsan", label: "Asia/Choibalsan" },
  { value: "Asia/Colombo", label: "Asia/Colombo" },
  { value: "Asia/Damascus", label: "Asia/Damascus" },
  { value: "Asia/Dhaka", label: "Asia/Dhaka" },
  { value: "Asia/Dili", label: "Asia/Dili" },
  { value: "Asia/Dubai", label: "Asia/Dubai" },
  { value: "Asia/Dushanbe", label: "Asia/Dushanbe" },
  { value: "Asia/Famagusta", label: "Asia/Famagusta" },
  { value: "Asia/Gaza", label: "Asia/Gaza" },
  { value: "Asia/Hebron", label: "Asia/Hebron" },
  { value: "Asia/Ho_Chi_Minh", label: "Asia/Ho_Chi_Minh" },
  { value: "Asia/Hong_Kong", label: "Asia/Hong_Kong" },
  { value: "Asia/Hovd", label: "Asia/Hovd" },
  { value: "Asia/Irkutsk", label: "Asia/Irkutsk" },
  { value: "Asia/Jakarta", label: "Asia/Jakarta" },
  { value: "Asia/Jayapura", label: "Asia/Jayapura" },
  { value: "Asia/Jerusalem", label: "Asia/Jerusalem" },
  { value: "Asia/Kabul", label: "Asia/Kabul" },
  { value: "Asia/Kamchatka", label: "Asia/Kamchatka" },
  { value: "Asia/Karachi", label: "Asia/Karachi" },
  { value: "Asia/Kathmandu", label: "Asia/Kathmandu" },
  { value: "Asia/Khandyga", label: "Asia/Khandyga" },
  { value: "Asia/Kolkata", label: "Asia/Kolkata" },
  { value: "Asia/Krasnoyarsk", label: "Asia/Krasnoyarsk" },
  { value: "Asia/Kuching", label: "Asia/Kuching" },
  { value: "Asia/Macau", label: "Asia/Macau" },
  { value: "Asia/Magadan", label: "Asia/Magadan" },
  { value: "Asia/Makassar", label: "Asia/Makassar" },
  { value: "Asia/Manila", label: "Asia/Manila" },
  { value: "Asia/Nicosia", label: "Asia/Nicosia" },
  { value: "Asia/Novokuznetsk", label: "Asia/Novokuznetsk" },
  { value: "Asia/Novosibirsk", label: "Asia/Novosibirsk" },
  { value: "Asia/Omsk", label: "Asia/Omsk" },
  { value: "Asia/Oral", label: "Asia/Oral" },
  { value: "Asia/Pontianak", label: "Asia/Pontianak" },
  { value: "Asia/Pyongyang", label: "Asia/Pyongyang" },
  { value: "Asia/Qatar", label: "Asia/Qatar" },
  { value: "Asia/Qostanay", label: "Asia/Qostanay" },
  { value: "Asia/Qyzylorda", label: "Asia/Qyzylorda" },
  { value: "Asia/Riyadh", label: "Asia/Riyadh" },
  { value: "Asia/Sakhalin", label: "Asia/Sakhalin" },
  { value: "Asia/Samarkand", label: "Asia/Samarkand" },
  { value: "Asia/Seoul", label: "Asia/Seoul" },
  { value: "Asia/Shanghai", label: "Asia/Shanghai" },
  { value: "Asia/Singapore", label: "Asia/Singapore" },
  { value: "Asia/Srednekolymsk", label: "Asia/Srednekolymsk" },
  { value: "Asia/Taipei", label: "Asia/Taipei" },
  { value: "Asia/Tashkent", label: "Asia/Tashkent" },
  { value: "Asia/Tbilisi", label: "Asia/Tbilisi" },
  { value: "Asia/Tehran", label: "Asia/Tehran" },
  { value: "Asia/Thimphu", label: "Asia/Thimphu" },
  { value: "Asia/Tokyo", label: "Asia/Tokyo" },
  { value: "Asia/Tomsk", label: "Asia/Tomsk" },
  { value: "Asia/Ulaanbaatar", label: "Asia/Ulaanbaatar" },
  { value: "Asia/Urumqi", label: "Asia/Urumqi" },
  { value: "Asia/Ust-Nera", label: "Asia/Ust-Nera" },
  { value: "Asia/Vladivostok", label: "Asia/Vladivostok" },
  { value: "Asia/Yakutsk", label: "Asia/Yakutsk" },
  { value: "Asia/Yangon", label: "Asia/Yangon" },
  { value: "Asia/Yekaterinburg", label: "Asia/Yekaterinburg" },
  { value: "Asia/Yerevan", label: "Asia/Yerevan" },
  { value: "Atlantic/Azores", label: "Atlantic/Azores" },
  { value: "Atlantic/Bermuda", label: "Atlantic/Bermuda" },
  { value: "Atlantic/Canary", label: "Atlantic/Canary" },
  { value: "Atlantic/Cape_Verde", label: "Atlantic/Cape_Verde" },
  { value: "Atlantic/Faroe", label: "Atlantic/Faroe" },
  { value: "Atlantic/Madeira", label: "Atlantic/Madeira" },
  { value: "Atlantic/South_Georgia", label: "Atlantic/South_Georgia" },
  { value: "Atlantic/Stanley", label: "Atlantic/Stanley" },
  { value: "Australia/Adelaide", label: "Australia/Adelaide" },
  { value: "Australia/Brisbane", label: "Australia/Brisbane" },
  { value: "Australia/Broken_Hill", label: "Australia/Broken_Hill" },
  { value: "Australia/Darwin", label: "Australia/Darwin" },
  { value: "Australia/Eucla", label: "Australia/Eucla" },
  { value: "Australia/Hobart", label: "Australia/Hobart" },
  { value: "Australia/Lindeman", label: "Australia/Lindeman" },
  { value: "Australia/Lord_Howe", label: "Australia/Lord_Howe" },
  { value: "Australia/Melbourne", label: "Australia/Melbourne" },
  { value: "Australia/Perth", label: "Australia/Perth" },
  { value: "Australia/Sydney", label: "Australia/Sydney" },
  { value: "CET", label: "CET" },
  { value: "CST6CDT", label: "CST6CDT" },
  { value: "EET", label: "EET" },
  { value: "EST", label: "EST" },
  { value: "EST5EDT", label: "EST5EDT" },
  { value: "Etc/GMT", label: "Etc/GMT" },
  { value: "Etc/GMT+1", label: "Etc/GMT+1" },
  { value: "Etc/GMT+10", label: "Etc/GMT+10" },
  { value: "Etc/GMT+11", label: "Etc/GMT+11" },
  { value: "Etc/GMT+12", label: "Etc/GMT+12" },
  { value: "Etc/GMT+2", label: "Etc/GMT+2" },
  { value: "Etc/GMT+3", label: "Etc/GMT+3" },
  { value: "Etc/GMT+4", label: "Etc/GMT+4" },
  { value: "Etc/GMT+5", label: "Etc/GMT+5" },
  { value: "Etc/GMT+6", label: "Etc/GMT+6" },
  { value: "Etc/GMT+7", label: "Etc/GMT+7" },
  { value: "Etc/GMT+8", label: "Etc/GMT+8" },
  { value: "Etc/GMT+9", label: "Etc/GMT+9" },
  { value: "Etc/GMT-1", label: "Etc/GMT-1" },
  { value: "Etc/GMT-10", label: "Etc/GMT-10" },
  { value: "Etc/GMT-11", label: "Etc/GMT-11" },
  { value: "Etc/GMT-12", label: "Etc/GMT-12" },
  { value: "Etc/GMT-13", label: "Etc/GMT-13" },
  { value: "Etc/GMT-14", label: "Etc/GMT-14" },
  { value: "Etc/GMT-2", label: "Etc/GMT-2" },
  { value: "Etc/GMT-3", label: "Etc/GMT-3" },
  { value: "Etc/GMT-4", label: "Etc/GMT-4" },
  { value: "Etc/GMT-5", label: "Etc/GMT-5" },
  { value: "Etc/GMT-6", label: "Etc/GMT-6" },
  { value: "Etc/GMT-7", label: "Etc/GMT-7" },
  { value: "Etc/GMT-8", label: "Etc/GMT-8" },
  { value: "Etc/GMT-9", label: "Etc/GMT-9" },
  { value: "Etc/UTC", label: "Etc/UTC" },
  { value: "Europe/Andorra", label: "Europe/Andorra" },
  { value: "Europe/Astrakhan", label: "Europe/Astrakhan" },
  { value: "Europe/Athens", label: "Europe/Athens" },
  { value: "Europe/Belgrade", label: "Europe/Belgrade" },
  { value: "Europe/Berlin", label: "Europe/Berlin" },
  { value: "Europe/Brussels", label: "Europe/Brussels" },
  { value: "Europe/Bucharest", label: "Europe/Bucharest" },
  { value: "Europe/Budapest", label: "Europe/Budapest" },
  { value: "Europe/Chisinau", label: "Europe/Chisinau" },
  { value: "Europe/Dublin", label: "Europe/Dublin" },
  { value: "Europe/Gibraltar", label: "Europe/Gibraltar" },
  { value: "Europe/Helsinki", label: "Europe/Helsinki" },
  { value: "Europe/Istanbul", label: "Europe/Istanbul" },
  { value: "Europe/Kaliningrad", label: "Europe/Kaliningrad" },
  { value: "Europe/Kirov", label: "Europe/Kirov" },
  { value: "Europe/Kiev", label: "Europe/Kiev" },
  { value: "Europe/Kirov", label: "Europe/Kirov" },
  { value: "Europe/Lisbon", label: "Europe/Lisbon" },
  { value: "Europe/London", label: "Europe/London" },
  { value: "Europe/Luxembourg", label: "Europe/Luxembourg" },
  { value: "Europe/Madrid", label: "Europe/Madrid" },
  { value: "Europe/Malta", label: "Europe/Malta" },
  { value: "Europe/Minsk", label: "Europe/Minsk" },
  { value: "Europe/Monaco", label: "Europe/Monaco" },
  { value: "Europe/Moscow", label: "Europe/Moscow" },
  { value: "Europe/Oslo", label: "Europe/Oslo" },
  { value: "Europe/Paris", label: "Europe/Paris" },
  { value: "Europe/Prague", label: "Europe/Prague" },
  { value: "Europe/Riga", label: "Europe/Riga" },
  { value: "Europe/Rome", label: "Europe/Rome" },
  { value: "Europe/Samara", label: "Europe/Samara" },
  { value: "Europe/Saratov", label: "Europe/Saratov" },
  { value: "Europe/Simferopol", label: "Europe/Simferopol" },
  { value: "Europe/Sofia", label: "Europe/Sofia" },
  { value: "Europe/Stockholm", label: "Europe/Stockholm" },
  { value: "Europe/Tallinn", label: "Europe/Tallinn" },
  { value: "Europe/Tirane", label: "Europe/Tirane" },
  { value: "Europe/Ulyanovsk", label: "Europe/Ulyanovsk" },
  { value: "Europe/Uzhgorod", label: "Europe/Uzhgorod" },
  { value: "Europe/Vienna", label: "Europe/Vienna" },
  { value: "Europe/Vilnius", label: "Europe/Vilnius" },
  { value: "Europe/Volgograd", label: "Europe/Volgograd" },
  { value: "Europe/Warsaw", label: "Europe/Warsaw" },
  { value: "Europe/Zaporozhye", label: "Europe/Zaporozhye" },
  { value: "Europe/Zurich", label: "Europe/Zurich" },
  { value: "Indian/Chagos", label: "Indian/Chagos" },
  { value: "Indian/Christmas", label: "Indian/Christmas" },
  { value: "Indian/Cocos", label: "Indian/Cocos" },
  { value: "Indian/Kerguelen", label: "Indian/Kerguelen" },
  { value: "Indian/Mahe", label: "Indian/Mahe" },
  { value: "Indian/Maldives", label: "Indian/Maldives" },
  { value: "Indian/Mauritius", label: "Indian/Mauritius" },
  { value: "Indian/Reunion", label: "Indian/Reunion" },
  { value: "MST", label: "MST" },
  { value: "MST7MDT", label: "MST7MDT" },
  { value: "PST8PDT", label: "PST8PDT" },
  { value: "Pacific/Apia", label: "Pacific/Apia" },
  { value: "Pacific/Auckland", label: "Pacific/Auckland" },
  { value: "Pacific/Bougainville", label: "Pacific/Bougainville" },
  { value: "Pacific/Chatham", label: "Pacific/Chatham" },
  { value: "Pacific/Chuuk", label: "Pacific/Chuuk" },
  { value: "Pacific/Easter", label: "Pacific/Easter" },
  { value: "Pacific/Efate", label: "Pacific/Efate" },
  { value: "Pacific/Enderbury", label: "Pacific/Enderbury" },
  { value: "Pacific/Fakaofo", label: "Pacific/Fakaofo" },
  { value: "Pacific/Fiji", label: "Pacific/Fiji" },
  { value: "Pacific/Funafuti", label: "Pacific/Funafuti" },
  { value: "Pacific/Galapagos", label: "Pacific/Galapagos" },
  { value: "Pacific/Gambier", label: "Pacific/Gambier" },
  { value: "Pacific/Guadalcanal", label: "Pacific/Guadalcanal" },
  { value: "Pacific/Guam", label: "Pacific/Guam" },
  { value: "Pacific/Honolulu", label: "Pacific/Honolulu" },
  { value: "Pacific/Kiritimati", label: "Pacific/Kiritimati" },
  { value: "Pacific/Kosrae", label: "Pacific/Kosrae" },
  { value: "Pacific/Kwajalein", label: "Pacific/Kwajalein" },
  { value: "Pacific/Majuro", label: "Pacific/Majuro" },
  { value: "Pacific/Marquesas", label: "Pacific/Marquesas" },
  { value: "Pacific/Midway", label: "Pacific/Midway" },
  { value: "Pacific/Nauru", label: "Pacific/Nauru" },
  { value: "Pacific/Niue", label: "Pacific/Niue" },
  { value: "Pacific/Norfolk", label: "Pacific/Norfolk" },
  { value: "Pacific/Noumea", label: "Pacific/Noumea" },
  { value: "Pacific/Pago_Pago", label: "Pacific/Pago_Pago" },
  { value: "Pacific/Palau", label: "Pacific/Palau" },
  { value: "Pacific/Pitcairn", label: "Pacific/Pitcairn" },
  { value: "Pacific/Pohnpei", label: "Pacific/Pohnpei" },
  { value: "Pacific/Port_Moresby", label: "Pacific/Port_Moresby" },
  { value: "Pacific/Rarotonga", label: "Pacific/Rarotonga" },
  { value: "Pacific/Saipan", label: "Pacific/Saipan" },
  { value: "Pacific/Tahiti", label: "Pacific/Tahiti" },
  { value: "Pacific/Tarawa", label: "Pacific/Tarawa" },
  { value: "Pacific/Tongatapu", label: "Pacific/Tongatapu" },
  { value: "Pacific/Wake", label: "Pacific/Wake" },
  { value: "Pacific/Wallis", label: "Pacific/Wallis" },
  { value: "WET", label: "WET" },
  { value: "UTC", label: "UTC" },
  { value: "Zulu", label: "Zulu" },
];

export const currencies = [
  { value: "AED", label: "AED" },
  { value: "AFN", label: "AFN" },
  { value: "ALL", label: "ALL" },
  { value: "AMD", label: "AMD" },
  { value: "ANG", label: "ANG" },
  { value: "AOA", label: "AOA" },
  { value: "ARS", label: "ARS" },
  { value: "AUD", label: "AUD" },
  { value: "AWG", label: "AWG" },
  { value: "AZN", label: "AZN" },
  { value: "BAM", label: "BAM" },
  { value: "BBD", label: "BBD" },
  { value: "BDT", label: "BDT" },
  { value: "BGN", label: "BGN" },
  { value: "BHD", label: "BHD" },
  { value: "BIF", label: "BIF" },
  { value: "BMD", label: "BMD" },
  { value: "BND", label: "BND" },
  { value: "BOB", label: "BOB" },
  { value: "BOV", label: "BOV" },
  { value: "BRL", label: "BRL" },
  { value: "BSD", label: "BSD" },
  { value: "BTN", label: "BTN" },
  { value: "BWP", label: "BWP" },
  { value: "BYN", label: "BYN" },
  { value: "BZD", label: "BZD" },
  { value: "CAD", label: "CAD" },
  { value: "CDF", label: "CDF" },
  { value: "CHE", label: "CHE" },
  { value: "CHF", label: "CHF" },
  { value: "CHW", label: "CHW" },
  { value: "CLF", label: "CLF" },
  { value: "CLP", label: "CLP" },
  { value: "CNY", label: "CNY" },
  { value: "COP", label: "COP" },
  { value: "COU", label: "COU" },
  { value: "CRC", label: "CRC" },
  { value: "CUC", label: "CUC" },
  { value: "CUP", label: "CUP" },
  { value: "CVE", label: "CVE" },
  { value: "CZK", label: "CZK" },
  { value: "DJF", label: "DJF" },
  { value: "DKK", label: "DKK" },
  { value: "DOP", label: "DOP" },
  { value: "DZD", label: "DZD" },
  { value: "EGP", label: "EGP" },
  { value: "ERN", label: "ERN" },
  { value: "ETB", label: "ETB" },
  { value: "EUR", label: "EUR" },
  { value: "FJD", label: "FJD" },
  { value: "FKP", label: "FKP" },
  { value: "GBP", label: "GBP" },
  { value: "GEL", label: "GEL" },
  { value: "GHS", label: "GHS" },
  { value: "GIP", label: "GIP" },
  { value: "GMD", label: "GMD" },
  { value: "GNF", label: "GNF" },
  { value: "GTQ", label: "GTQ" },
  { value: "GYD", label: "GYD" },
  { value: "HKD", label: "HKD" },
  { value: "HNL", label: "HNL" },
  { value: "HRK", label: "HRK" },
  { value: "HTG", label: "HTG" },
  { value: "HUF", label: "HUF" },
  { value: "IDR", label: "IDR" },
  { value: "ILS", label: "ILS" },
  { value: "INR", label: "INR" },
  { value: "IQD", label: "IQD" },
  { value: "IRR", label: "IRR" },
  { value: "ISK", label: "ISK" },
  { value: "JMD", label: "JMD" },
  { value: "JOD", label: "JOD" },
  { value: "JPY", label: "JPY" },
  { value: "KES", label: "KES" },
  { value: "KGS", label: "KGS" },
  { value: "KHR", label: "KHR" },
  { value: "KMF", label: "KMF" },
  { value: "KPW", label: "KPW" },
  { value: "KRW", label: "KRW" },
  { value: "KWD", label: "KWD" },
  { value: "KYD", label: "KYD" },
  { value: "KZT", label: "KZT" },
  { value: "LAK", label: "LAK" },
  { value: "LBP", label: "LBP" },
  { value: "LKR", label: "LKR" },
  { value: "LRD", label: "LRD" },
  { value: "LSL", label: "LSL" },
  { value: "LYD", label: "LYD" },
  { value: "MAD", label: "MAD" },
  { value: "MDL", label: "MDL" },
  { value: "MGA", label: "MGA" },
  { value: "MKD", label: "MKD" },
  { value: "MMK", label: "MMK" },
  { value: "MNT", label: "MNT" },
  { value: "MOP", label: "MOP" },
  { value: "MRU", label: "MRU" },
  { value: "MUR", label: "MUR" },
  { value: "MVR", label: "MVR" },
  { value: "MWK", label: "MWK" },
  { value: "MXN", label: "MXN" },
  { value: "MXV", label: "MXV" },
  { value: "MYR", label: "MYR" },
  { value: "MZN", label: "MZN" },
  { value: "NAD", label: "NAD" },
  { value: "NGN", label: "NGN" },
  { value: "NIO", label: "NIO" },
  { value: "NOK", label: "NOK" },
  { value: "NPR", label: "NPR" },
  { value: "NZD", label: "NZD" },
  { value: "OMR", label: "OMR" },
  { value: "PAB", label: "PAB" },
  { value: "PEN", label: "PEN" },
  { value: "PGK", label: "PGK" },
  { value: "PHP", label: "PHP" },
  { value: "PKR", label: "PKR" },
  { value: "PLN", label: "PLN" },
  { value: "PYG", label: "PYG" },
  { value: "QAR", label: "QAR" },
  { value: "RON", label: "RON" },
  { value: "RSD", label: "RSD" },
  { value: "RUB", label: "RUB" },
  { value: "RWF", label: "RWF" },
  { value: "SAR", label: "SAR" },
  { value: "SBD", label: "SBD" },
  { value: "SCR", label: "SCR" },
  { value: "SDG", label: "SDG" },
  { value: "SEK", label: "SEK" },
  { value: "SGD", label: "SGD" },
  { value: "SHP", label: "SHP" },
  { value: "SLL", label: "SLL" },
  { value: "SOS", label: "SOS" },
  { value: "SRD", label: "SRD" },
  { value: "SSP", label: "SSP" },
  { value: "STN", label: "STN" },
  { value: "SVC", label: "SVC" },
  { value: "SYP", label: "SYP" },
  { value: "SZL", label: "SZL" },
  { value: "THB", label: "THB" },
  { value: "TJS", label: "TJS" },
  { value: "TMT", label: "TMT" },
  { value: "TND", label: "TND" },
  { value: "TOP", label: "TOP" },
  { value: "TRY", label: "TRY" },
  { value: "TTD", label: "TTD" },
  { value: "TWD", label: "TWD" },
  { value: "TZS", label: "TZS" },
  { value: "UAH", label: "UAH" },
  { value: "UGX", label: "UGX" },
  { value: "USD", label: "USD" },
  { value: "USN", label: "USN" },
  { value: "UYI", label: "UYI" },
  { value: "UYU", label: "UYU" },
  { value: "UYW", label: "UYW" },
  { value: "UZS", label: "UZS" },
  { value: "VES", label: "VES" },
  { value: "VND", label: "VND" },
  { value: "VUV", label: "VUV" },
  { value: "WST", label: "WST" },
  { value: "XAF", label: "XAF" },
  { value: "XAG", label: "XAG" },
  { value: "XAU", label: "XAU" },
  { value: "XBA", label: "XBA" },
  { value: "XBB", label: "XBB" },
  { value: "XBC", label: "XBC" },
  { value: "XBD", label: "XBD" },
  { value: "XCD", label: "XCD" },
  { value: "XDR", label: "XDR" },
  { value: "XOF", label: "XOF" },
  { value: "XPD", label: "XPD" },
  { value: "XPF", label: "XPF" },
  { value: "XPT", label: "XPT" },
  { value: "XSU", label: "XSU" },
  { value: "XTS", label: "XTS" },
  { value: "XUA", label: "XUA" },
  { value: "XXX", label: "XXX" },
  { value: "YER", label: "YER" },
  { value: "ZAR", label: "ZAR" },
  { value: "ZMW", label: "ZMW" },
  { value: "ZWL", label: "ZWL" },
];

export const countries = [
  { value: "Andorra", label: "Andorra" },
  { value: "United Arab Emirates", label: "United Arab Emirates" },
  { value: "Afghanistan", label: "Afghanistan" },
  { value: "Antigua and Barbuda", label: "Antigua and Barbuda" },
  { value: "Anguilla", label: "Anguilla" },
  { value: "Albania", label: "Albania" },
  { value: "Armenia", label: "Armenia" },
  { value: "Angola", label: "Angola" },
  { value: "Antarctica", label: "Antarctica" },
  { value: "Argentina", label: "Argentina" },
  { value: "American Samoa", label: "American Samoa" },
  { value: "Austria", label: "Austria" },
  { value: "Australia", label: "Australia" },
  { value: "Aruba", label: "Aruba" },
  { value: "Åland Islands", label: "Åland Islands" },
  { value: "Azerbaijan", label: "Azerbaijan" },
  { value: "Bosnia and Herzegovina", label: "Bosnia and Herzegovina" },
  { value: "Barbados", label: "Barbados" },
  { value: "Bangladesh", label: "Bangladesh" },
  { value: "Belgium", label: "Belgium" },
  { value: "Burkina Faso", label: "Burkina Faso" },
  { value: "Bulgaria", label: "Bulgaria" },
  { value: "Bahrain", label: "Bahrain" },
  { value: "Burundi", label: "Burundi" },
  { value: "Benin", label: "Benin" },
  { value: "Saint Barthélemy", label: "Saint Barthélemy" },
  { value: "Bermuda", label: "Bermuda" },
  { value: "Brunei Darussalam", label: "Brunei Darussalam" },
  {
    value: "Bolivia, Plurinational State of",
    label: "Bolivia, Plurinational State of",
  },
  {
    value: "Bonaire, Sint Eustatius and Saba",
    label: "Bonaire, Sint Eustatius and Saba",
  },
  { value: "Brazil", label: "Brazil" },
  { value: "Bahamas", label: "Bahamas" },
  { value: "Bhutan", label: "Bhutan" },
  { value: "Bouvet Island", label: "Bouvet Island" },
  { value: "Botswana", label: "Botswana" },
  { value: "Belarus", label: "Belarus" },
  { value: "Belize", label: "Belize" },
  { value: "Canada", label: "Canada" },
  { value: "Cocos (Keeling) Islands", label: "Cocos (Keeling) Islands" },
  {
    value: "Congo, Democratic Republic of the",
    label: "Congo, Democratic Republic of the",
  },
  { value: "Central African Republic", label: "Central African Republic" },
  { value: "Congo", label: "Congo" },
  { value: "Switzerland", label: "Switzerland" },
  { value: "Côte d'Ivoire", label: "Côte d'Ivoire" },
  { value: "Cook Islands", label: "Cook Islands" },
  { value: "Chile", label: "Chile" },
  { value: "Cameroon", label: "Cameroon" },
  { value: "China", label: "China" },
  { value: "Colombia", label: "Colombia" },
  { value: "Costa Rica", label: "Costa Rica" },
  { value: "Cuba", label: "Cuba" },
  { value: "Cabo Verde", label: "Cabo Verde" },
  { value: "Curaçao", label: "Curaçao" },
  { value: "Christmas Island", label: "Christmas Island" },
  { value: "Cyprus", label: "Cyprus" },
  { value: "Czechia", label: "Czechia" },
  { value: "Germany", label: "Germany" },
  { value: "Djibouti", label: "Djibouti" },
  { value: "Denmark", label: "Denmark" },
  { value: "Dominica", label: "Dominica" },
  { value: "Dominican Republic", label: "Dominican Republic" },
  { value: "Algeria", label: "Algeria" },
  { value: "Ecuador", label: "Ecuador" },
  { value: "Estonia", label: "Estonia" },
  { value: "Egypt", label: "Egypt" },
  { value: "Western Sahara", label: "Western Sahara" },
  { value: "Eritrea", label: "Eritrea" },
  { value: "Spain", label: "Spain" },
  { value: "Ethiopia", label: "Ethiopia" },
  { value: "Finland", label: "Finland" },
  { value: "Fiji", label: "Fiji" },
  {
    value: "Falkland Islands (Malvinas)",
    label: "Falkland Islands (Malvinas)",
  },
  {
    value: "Micronesia, Federated States of",
    label: "Micronesia, Federated States of",
  },
  { value: "Faroe Islands", label: "Faroe Islands" },
  { value: "France", label: "France" },
  { value: "Gabon", label: "Gabon" },
  {
    value: "United Kingdom of Great Britain and Northern Ireland",
    label: "United Kingdom of Great Britain and Northern Ireland",
  },
  { value: "Grenada", label: "Grenada" },
  { value: "Georgia", label: "Georgia" },
  { value: "French Guiana", label: "French Guiana" },
  { value: "Guernsey", label: "Guernsey" },
  { value: "Ghana", label: "Ghana" },
  { value: "Gibraltar", label: "Gibraltar" },
  { value: "Greenland", label: "Greenland" },
  { value: "Gambia", label: "Gambia" },
  { value: "Guinea", label: "Guinea" },
  { value: "Guadeloupe", label: "Guadeloupe" },
  { value: "Equatorial Guinea", label: "Equatorial Guinea" },
  { value: "Greece", label: "Greece" },
  {
    value: "South Georgia and the South Sandwich Islands",
    label: "South Georgia and the South Sandwich Islands",
  },
  { value: "Guatemala", label: "Guatemala" },
  { value: "Guam", label: "Guam" },
  { value: "Guinea-Bissau", label: "Guinea-Bissau" },
  { value: "Guyana", label: "Guyana" },
  { value: "Hong Kong", label: "Hong Kong" },
  {
    value: "Heard Island and McDonald Islands",
    label: "Heard Island and McDonald Islands",
  },
  { value: "Honduras", label: "Honduras" },
  { value: "Croatia", label: "Croatia" },
  { value: "Haiti", label: "Haiti" },
  { value: "Hungary", label: "Hungary" },
  { value: "Indonesia", label: "Indonesia" },
  { value: "Ireland", label: "Ireland" },
  { value: "Israel", label: "Israel" },
  { value: "Isle of Man", label: "Isle of Man" },
  { value: "India", label: "India" },
  {
    value: "British Indian Ocean Territory",
    label: "British Indian Ocean Territory",
  },
  { value: "Iraq", label: "Iraq" },
  { value: "Iran, Islamic Republic of", label: "Iran, Islamic Republic of" },
  { value: "Iceland", label: "Iceland" },
  { value: "Italy", label: "Italy" },
  { value: "Jersey", label: "Jersey" },
  { value: "Jamaica", label: "Jamaica" },
  { value: "Jordan", label: "Jordan" },
  { value: "Japan", label: "Japan" },
  { value: "Kenya", label: "Kenya" },
  { value: "Kyrgyzstan", label: "Kyrgyzstan" },
  { value: "Cambodia", label: "Cambodia" },
  { value: "Kiribati", label: "Kiribati" },
  { value: "Comoros", label: "Comoros" },
  { value: "Saint Kitts and Nevis", label: "Saint Kitts and Nevis" },
  {
    value: "Korea, Democratic People's Republic of",
    label: "Korea, Democratic People's Republic of",
  },
  { value: "Korea, Republic of", label: "Korea, Republic of" },
  { value: "Kuwait", label: "Kuwait" },
  { value: "Cayman Islands", label: "Cayman Islands" },
  { value: "Kazakhstan", label: "Kazakhstan" },
  {
    value: "Lao People's Democratic Republic",
    label: "Lao People's Democratic Republic",
  },
  { value: "Lebanon", label: "Lebanon" },
  { value: "Saint Lucia", label: "Saint Lucia" },
  { value: "Liechtenstein", label: "Liechtenstein" },
  { value: "Sri Lanka", label: "Sri Lanka" },
  { value: "Liberia", label: "Liberia" },
  { value: "Lesotho", label: "Lesotho" },
  { value: "Lithuania", label: "Lithuania" },
  { value: "Luxembourg", label: "Luxembourg" },
  { value: "Latvia", label: "Latvia" },
  { value: "Libya", label: "Libya" },
  { value: "Morocco", label: "Morocco" },
  { value: "Monaco", label: "Monaco" },
  { value: "Moldova, Republic of", label: "Moldova, Republic of" },
  { value: "Montenegro", label: "Montenegro" },
  {
    value: "Saint Martin, (French part)",
    label: "Saint Martin, (French part)",
  },
  { value: "Madagascar", label: "Madagascar" },
  { value: "Marshall Islands", label: "Marshall Islands" },
  { value: "North Macedonia", label: "North Macedonia" },
  { value: "Mali", label: "Mali" },
  { value: "Myanmar", label: "Myanmar" },
  { value: "Mongolia", label: "Mongolia" },
  { value: "Macao", label: "Macao" },
  { value: "Northern Mariana Islands", label: "Northern Mariana Islands" },
  { value: "Martinique", label: "Martinique" },
  { value: "Mauritania", label: "Mauritania" },
  { value: "Montserrat", label: "Montserrat" },
  { value: "Malta", label: "Malta" },
  { value: "Mauritius", label: "Mauritius" },
  { value: "Maldives", label: "Maldives" },
  { value: "Malawi", label: "Malawi" },
  { value: "Mexico", label: "Mexico" },
  { value: "Malaysia", label: "Malaysia" },
  { value: "Mozambique", label: "Mozambique" },
  { value: "Namibia", label: "Namibia" },
  { value: "New Caledonia", label: "New Caledonia" },
  { value: "Niger", label: "Niger" },
  { value: "Norfolk Island", label: "Norfolk Island" },
  { value: "Nigeria", label: "Nigeria" },
  { value: "Nicaragua", label: "Nicaragua" },
  { value: "Netherlands", label: "Netherlands" },
  { value: "Norway", label: "Norway" },
  { value: "Nepal", label: "Nepal" },
  { value: "Nauru", label: "Nauru" },
  { value: "Niue", label: "Niue" },
  { value: "New Zealand", label: "New Zealand" },
  { value: "Oman", label: "Oman" },
  { value: "Panama", label: "Panama" },
  { value: "Peru", label: "Peru" },
  { value: "French Polynesia", label: "French Polynesia" },
  { value: "Papua New Guinea", label: "Papua New Guinea" },
  { value: "Philippines", label: "Philippines" },
  { value: "Pakistan", label: "Pakistan" },
  { value: "Poland", label: "Poland" },
  { value: "Saint Pierre and Miquelon", label: "Saint Pierre and Miquelon" },
  { value: "Pitcairn", label: "Pitcairn" },
  { value: "Puerto Rico", label: "Puerto Rico" },
  { value: "Palestine, State of", label: "Palestine, State of" },
  { value: "Portugal", label: "Portugal" },
  { value: "Palau", label: "Palau" },
  { value: "Paraguay", label: "Paraguay" },
  { value: "Qatar", label: "Qatar" },
  { value: "Réunion", label: "Réunion" },
  { value: "Romania", label: "Romania" },
  { value: "Serbia", label: "Serbia" },
  { value: "Russian Federation", label: "Russian Federation" },
  { value: "Rwanda", label: "Rwanda" },
  { value: "Saudi Arabia", label: "Saudi Arabia" },
  { value: "Solomon Islands", label: "Solomon Islands" },
  { value: "Seychelles", label: "Seychelles" },
  { value: "Sudan", label: "Sudan" },
  { value: "Sweden", label: "Sweden" },
  { value: "Singapore", label: "Singapore" },
  {
    value: "Saint Helena, Ascension and Tristan da Cunha",
    label: "Saint Helena, Ascension and Tristan da Cunha",
  },
  { value: "Slovenia", label: "Slovenia" },
  { value: "Svalbard and Jan Mayen", label: "Svalbard and Jan Mayen" },
  { value: "Slovakia", label: "Slovakia" },
  { value: "Sierra Leone", label: "Sierra Leone" },
  { value: "San Marino", label: "San Marino" },
  { value: "Senegal", label: "Senegal" },
  { value: "Somalia", label: "Somalia" },
  { value: "Suriname", label: "Suriname" },
  { value: "South Sudan", label: "South Sudan" },
  { value: "Sao Tome and Principe", label: "Sao Tome and Principe" },
  { value: "El Salvador", label: "El Salvador" },
  { value: "Sint Maarten, (Dutch part)", label: "Sint Maarten, (Dutch part)" },
  { value: "Syrian Arab Republic", label: "Syrian Arab Republic" },
  { value: "Eswatini", label: "Eswatini" },
  { value: "Turks and Caicos Islands", label: "Turks and Caicos Islands" },
  { value: "Chad", label: "Chad" },
  {
    value: "French Southern Territories",
    label: "French Southern Territories",
  },
  { value: "Togo", label: "Togo" },
  { value: "Thailand", label: "Thailand" },
  { value: "Tajikistan", label: "Tajikistan" },
  { value: "Tokelau", label: "Tokelau" },
  { value: "Timor-Leste", label: "Timor-Leste" },
  { value: "Turkmenistan", label: "Turkmenistan" },
  { value: "Tunisia", label: "Tunisia" },
  { value: "Tonga", label: "Tonga" },
  { value: "Türkiye", label: "Türkiye" },
  { value: "Trinidad and Tobago", label: "Trinidad and Tobago" },
  { value: "Tuvalu", label: "Tuvalu" },
  { value: "Taiwan, Province of China", label: "Taiwan, Province of China" },
  {
    value: "Tanzania, United Republic of",
    label: "Tanzania, United Republic of",
  },
  { value: "Ukraine", label: "Ukraine" },
  { value: "Uganda", label: "Uganda" },
  {
    value: "United States Minor Outlying Islands",
    label: "United States Minor Outlying Islands",
  },
  { value: "United States of America", label: "United States of America" },
  { value: "Uruguay", label: "Uruguay" },
  { value: "Uzbekistan", label: "Uzbekistan" },
  { value: "Holy See", label: "Holy See" },
  {
    value: "Saint Vincent and the Grenadines",
    label: "Saint Vincent and the Grenadines",
  },
  {
    value: "Venezuela, Bolivarian Republic of",
    label: "Venezuela, Bolivarian Republic of",
  },
  { value: "Virgin Islands, British", label: "Virgin Islands, British" },
  { value: "Virgin Islands, U.S.", label: "Virgin Islands, U.S." },
  { value: "Viet Nam", label: "Viet Nam" },
  { value: "Vanuatu", label: "Vanuatu" },
  { value: "Wallis and Futuna", label: "Wallis and Futuna" },
  { value: "Samoa", label: "Samoa" },
  { value: "Yemen", label: "Yemen" },
  { value: "Mayotte", label: "Mayotte" },
];

export const businessCategories = [
  { value: "Animal Shelter", label: "AnimalShelter" },
  { value: "Archive Organization", label: "ArchiveOrganization" },
  { value: "Auto Body Shop", label: "AutomotiveBusiness > AutoBodyShop" },
  { value: "Auto Dealer", label: "AutomotiveBusiness > AutoDealer" },
  { value: "Auto Parts Store", label: "AutomotiveBusiness > AutoPartsStore" },
  { value: "Auto Repair", label: "AutomotiveBusiness > AutoRepair" },
  { value: "Auto Wash", label: "AutomotiveBusiness > AutoWash" },
  { value: "Gas Station", label: "AutomotiveBusiness > GasStation" },
  {
    value: "Motorcycle Dealer",
    label: "AutomotiveBusiness > MotorcycleDealer",
  },
  {
    value: "Motorcycle Repair",
    label: "AutomotiveBusiness > MotorcycleRepair",
  },
  { value: "Other", label: "AutomotiveBusiness > Other" },
  { value: "Child Care", label: "ChildCare" },
  { value: "Dentist", label: "Dentist" },
  { value: "Dry Cleaning Or Laundry", label: "DryCleaningOrLaundry" },
  { value: "Fire Station", label: "EmergencyService > FireStation" },
  { value: "Hospital", label: "EmergencyService > Hospital" },
  { value: "Police Station", label: "EmergencyService > PoliceStation" },
  { value: "Other", label: "EmergencyService > Other" },
  { value: "Employment Agency", label: "EmploymentAgency" },
  {
    value: "Adult Entertainment",
    label: "EntertainmentBusiness > AdultEntertainment",
  },
  { value: "Amusement Park", label: "EntertainmentBusiness > AmusementPark" },
  { value: "Art Gallery", label: "EntertainmentBusiness > ArtGallery" },
  { value: "Casino", label: "EntertainmentBusiness > Casino" },
  { value: "Comedy Club", label: "EntertainmentBusiness > ComedyClub" },
  { value: "Movie Theater", label: "EntertainmentBusiness > MovieTheater" },
  { value: "Night Club", label: "EntertainmentBusiness > NightClub" },
  { value: "Other", label: "EntertainmentBusiness > Other" },
  {
    value: "Accounting Service",
    label: "FinancialService > AccountingService",
  },
  { value: "Automated Teller", label: "FinancialService > AutomatedTeller" },
  {
    value: "Bank Or Credit Union",
    label: "FinancialService > BankOrCreditUnion",
  },
  { value: "Insurance Agency", label: "FinancialService > InsuranceAgency" },
  { value: "Other", label: "FinancialService > Other" },
  { value: "Bakery", label: "FoodEstablishment > Bakery" },
  { value: "Bar Or Pub", label: "FoodEstablishment > BarOrPub" },
  { value: "Brewery", label: "FoodEstablishment > Brewery" },
  {
    value: "Cafe Or Coffee Shop",
    label: "FoodEstablishment > CafeOrCoffeeShop",
  },
  { value: "Distillery", label: "FoodEstablishment > Distillery" },
  {
    value: "Fast Food Restaurant",
    label: "FoodEstablishment > FastFoodRestaurant",
  },
  { value: "Ice Cream Shop", label: "FoodEstablishment > IceCreamShop" },
  { value: "Restaurant", label: "FoodEstablishment > Restaurant" },
  { value: "Winery", label: "FoodEstablishment > Winery" },
  { value: "Other", label: "FoodEstablishment > Other" },
  { value: "Post Office", label: "GovernmentOffice > PostOffice" },
  { value: "Other", label: "GovernmentOffice > Other" },
  { value: "Beauty Salon", label: "HealthAndBeautyBusiness > BeautySalon" },
  { value: "Day Spa", label: "HealthAndBeautyBusiness > DaySpa" },
  { value: "Hair Salon", label: "HealthAndBeautyBusiness > HairSalon" },
  { value: "Health Club", label: "HealthAndBeautyBusiness > HealthClub" },
  { value: "Nail Salon", label: "HealthAndBeautyBusiness > NailSalon" },
  { value: "Tattoo Parlor", label: "HealthAndBeautyBusiness > TattooParlor" },
  { value: "Other", label: "HealthAndBeautyBusiness > Other" },
  { value: "Electrician", label: "HomeAndConstructionBusiness > Electrician" },
  {
    value: "General Contractor",
    label: "HomeAndConstructionBusiness > GeneralContractor",
  },
  {
    value: "HVAC Business",
    label: "HomeAndConstructionBusiness > HVACBusiness",
  },
  {
    value: "House Painter",
    label: "HomeAndConstructionBusiness > HousePainter",
  },
  { value: "Locksmith", label: "HomeAndConstructionBusiness > Locksmith" },
  {
    value: "Moving Company",
    label: "HomeAndConstructionBusiness > MovingCompany",
  },
  { value: "Plumber", label: "HomeAndConstructionBusiness > Plumber" },
  {
    value: "Roofing Contractor",
    label: "HomeAndConstructionBusiness > RoofingContractor",
  },
  { value: "Other", label: "HomeAndConstructionBusiness > Other" },
  { value: "Internet Cafe", label: "InternetCafe" },
  { value: "Attorney", label: "LegalService > Attorney" },
  { value: "Notary", label: "LegalService > Notary" },
  { value: "Other", label: "LegalService > Other" },
  { value: "Library", label: "Library" },
  { value: "Local Business", label: "LocalBusiness" },
  { value: "Bed And Breakfast", label: "LodgingBusiness > BedAndBreakfast" },
  { value: "Campground", label: "LodgingBusiness > Campground" },
  { value: "Hostel", label: "LodgingBusiness > Hostel" },
  { value: "Hotel", label: "LodgingBusiness > Hotel" },
  { value: "Motel", label: "LodgingBusiness > Motel" },
  { value: "Resort", label: "LodgingBusiness > Resort" },
  { value: "Other", label: "LodgingBusiness > Other" },
  { value: "Community Health", label: "MedicalBusiness > CommunityHealth" },
  { value: "Dentist", label: "MedicalBusiness > Dentist" },
  { value: "Dermatology", label: "MedicalBusiness > Dermatology" },
  { value: "Diet Nutrition", label: "MedicalBusiness > DietNutrition" },
  { value: "Emergency", label: "MedicalBusiness > Emergency" },
  { value: "Geriatric", label: "MedicalBusiness > Geriatric" },
  { value: "Gynecologic", label: "MedicalBusiness > Gynecologic" },
  { value: "Medical Clinic", label: "MedicalBusiness > MedicalClinic" },
  { value: "Midwifery", label: "MedicalBusiness > Midwifery" },
  { value: "Nursing", label: "MedicalBusiness > Nursing" },
  { value: "Obstetric", label: "MedicalBusiness > Obstetric" },
  { value: "Oncologic", label: "MedicalBusiness > Oncologic" },
  { value: "Optician", label: "MedicalBusiness > Optician" },
  { value: "Optometric", label: "MedicalBusiness > Optometric" },
  { value: "Otolaryngologic", label: "MedicalBusiness > Otolaryngologic" },
  { value: "Pediatric", label: "MedicalBusiness > Pediatric" },
  { value: "Pharmacy", label: "MedicalBusiness > Pharmacy" },
  { value: "Physician", label: "MedicalBusiness > Physician" },
  { value: "Physiotherapy", label: "MedicalBusiness > Physiotherapy" },
  { value: "Plastic Surgery", label: "MedicalBusiness > PlasticSurgery" },
  { value: "Podiatric", label: "MedicalBusiness > Podiatric" },
  { value: "Primary Care", label: "MedicalBusiness > PrimaryCare" },
  { value: "Psychiatric", label: "MedicalBusiness > Psychiatric" },
  { value: "Public Health", label: "MedicalBusiness > PublicHealth" },
  { value: "Other", label: "MedicalBusiness > Other" },
  { value: "Professional Service", label: "ProfessionalService" },
  { value: "Radio Station", label: "RadioStation" },
  { value: "Real Estate Agent", label: "RealEstateAgent" },
  { value: "Recycling Center", label: "RecyclingCenter" },
  { value: "Self Storage", label: "SelfStorage" },
  { value: "Shopping Center", label: "ShoppingCenter" },
  { value: "Bowling Alley", label: "SportsActivityLocation > BowlingAlley" },
  { value: "Exercise Gym", label: "SportsActivityLocation > ExerciseGym" },
  { value: "Golf Course", label: "SportsActivityLocation > GolfCourse" },
  { value: "Health Club", label: "SportsActivityLocation > HealthClub" },
  {
    value: "Public Swimming Pool",
    label: "SportsActivityLocation > PublicSwimmingPool",
  },
  { value: "Ski Resort", label: "SportsActivityLocation > SkiResort" },
  { value: "Sports Club", label: "SportsActivityLocation > SportsClub" },
  {
    value: "Stadium Or Arena",
    label: "SportsActivityLocation > StadiumOrArena",
  },
  { value: "Tennis Complex", label: "SportsActivityLocation > TennisComplex" },
  { value: "Other", label: "SportsActivityLocation > Other" },
  { value: "Auto Parts Store", label: "Store > AutoPartsStore" },
  { value: "Bike Store", label: "Store > BikeStore" },
  { value: "Book Store", label: "Store > BookStore" },
  { value: "Clothing Store", label: "Store > ClothingStore" },
  { value: "Computer Store", label: "Store > ComputerStore" },
  { value: "Convenience Store", label: "Store > ConvenienceStore" },
  { value: "Department Store", label: "Store > DepartmentStore" },
  { value: "Electronics Store", label: "Store > ElectronicsStore" },
  { value: "Florist", label: "Store > Florist" },
  { value: "Furniture Store", label: "Store > FurnitureStore" },
  { value: "Garden Store", label: "Store > GardenStore" },
  { value: "Grocery Store", label: "Store > GroceryStore" },
  { value: "Hardware Store", label: "Store > HardwareStore" },
  { value: "Hobby Shop", label: "Store > HobbyShop" },
  { value: "Home Goods Store", label: "Store > HomeGoodsStore" },
  { value: "Jewelry Store", label: "Store > JewelryStore" },
  { value: "Liquor Store", label: "Store > LiquorStore" },
  { value: "Men's Clothing Store", label: "Store > MensClothingStore" },
  { value: "Mobile Phone Store", label: "Store > MobilePhoneStore" },
  { value: "Movie Rental Store", label: "Store > MovieRentalStore" },
  { value: "Music Store", label: "Store > MusicStore" },
  { value: "Office Equipment Store", label: "Store > OfficeEquipmentStore" },
  { value: "Outlet Store", label: "Store > OutletStore" },
  { value: "Pawn Shop", label: "Store > PawnShop" },
  { value: "Pet Store", label: "Store > PetStore" },
  { value: "Shoe Store", label: "Store > ShoeStore" },
  { value: "Sporting Goods Store", label: "Store > SportingGoodsStore" },
  { value: "Tire Shop", label: "Store > TireShop" },
  { value: "Toy Store", label: "Store > ToyStore" },
  { value: "Wholesale Store", label: "Store > WholesaleStore" },
  { value: "Other", label: "Store > Other" },
  { value: "Television Station", label: "TelevisionStation" },
  { value: "Tourist Information Center", label: "TouristInformationCenter" },
  { value: "Travel Agency", label: "TravelAgency" },
];


export const organizations = [
  { value: "Airline", label: "Airline" },
  { value: "Consortium", label: "Consortium" },
  { value: "Corporation", label: "Corporation" },
  { value: "CollegeOrUniversity", label: "EducationalOrganization > CollegeOrUniversity" },
  { value: "ElementarySchool", label: "EducationalOrganization > ElementarySchool" },
  { value: "HighSchool", label: "EducationalOrganization > HighSchool" },
  { value: "MiddleSchool", label: "EducationalOrganization > MiddleSchool" },
  { value: "Preschool", label: "EducationalOrganization > Preschool" },
  { value: "School", label: "EducationalOrganization > School" },
  { value: "EducationalOrganization > Other", label: "EducationalOrganization > Other" },
  { value: "FundingScheme", label: "FundingScheme" },
  { value: "GovernmentOrganization", label: "GovernmentOrganization" },
  { value: "LibrarySystem", label: "LibrarySystem" },
  { value: "MedicalOrganization", label: "MedicalOrganization" },
  { value: "NGO", label: "NGO" },
  { value: "Dentist", label: "NewsMediaOrganization > Dentist" },
  { value: "DiagnosticLab", label: "NewsMediaOrganization > DiagnosticLab" },
  { value: "Hospital", label: "NewsMediaOrganization > Hospital" },
  { value: "MedicalClinic", label: "NewsMediaOrganization > MedicalClinic" },
  { value: "Pharmacy", label: "NewsMediaOrganization > Pharmacy" },
  { value: "Physician", label: "NewsMediaOrganization > Physician" },
  { value: "VeterinaryCare", label: "NewsMediaOrganization > VeterinaryCare" },
  { value: "NewsMediaOrganization > Other", label: "NewsMediaOrganization > Other" },
  { value: "Organization", label: "Organization" },
  { value: "DanceGroup", label: "PerformingGroup > DanceGroup" },
  { value: "MusicGroup", label: "PerformingGroup > MusicGroup" },
  { value: "TheaterGroup", label: "PerformingGroup > TheaterGroup" },
  { value: "PerformingGroup > Other", label: "PerformingGroup > Other" },
  { value: "FundingAgency", label: "Project > FundingAgency" },
  { value: "ResearchProject", label: "Project > ResearchProject" },
  { value: "Project > Other", label: "Project > Other" },
  { value: "SportsTeam", label: "SportsOrganization > SportsTeam" },
  { value: "SportsOrganization > Other", label: "SportsOrganization > Other" },
  { value: "WorkersUnion", label: "WorkersUnion" }
];
