// import { Inter } from "next/font/google";
// import "./globals.css";
// import MiniDrawer from "./components/Sidebar";
// import Footer from "./components/Footer";
// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className} style={{ backgroundColor: "black" }}>
//         <>
//           <div style={{ display: "flex", width: "100%" }}>
//             {" "}
//             <MiniDrawer />
//             <div style={{ display: "flex", width: "100%" }}>
//               <div className=" mt-20 ml-0 w-full">
//                 {children}
//                 <Footer />
//               </div>
//             </div>
//           </div>
//         </>
//       </body>
//     </html>
//   );
// }
import { Inter } from "next/font/google";
import "./globals.css";
import MiniDrawer from "./components/Sidebar";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ backgroundColor: "black", margin: 0, padding: 0 }}>
        <div style={{ display: "flex", minHeight: "100vh" }}>
          <MiniDrawer />
          {/* Remove the fixed marginLeft - let the drawer handle spacing */}
          <div 
            style={{ 
              flexGrow: 1,
              marginTop: "64px", // Keep only the top margin for AppBar
              minHeight: "100vh",
              display: "flex",
              flexDirection: "column",
              width: "100%", // Ensure full width
            }}
          >
            <div style={{ flexGrow: 1 }}>
              {children}
            </div>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
