


// import { Inter } from "next/font/google";
// import "./globals.css";
// import MiniDrawer from "./components/Sidebar";
// import Footer from "./components/Footer";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className} style={{ backgroundColor: "black", margin: 0, padding: 0 }}>
//         <div style={{ display: "flex", minHeight: "100vh" }}>
//           <MiniDrawer />
//           {/* Remove the fixed marginLeft - let the drawer handle spacing */}
//           <div 
//             style={{ 
//               flexGrow: 1,
//               marginTop: "64px", // Keep only the top margin for AppBar
//               minHeight: "100vh",
//               display: "flex",
//               flexDirection: "column",
//               width: "100%", // Ensure full width
//             }}
//           >
//             <div style={{ flexGrow: 1 }}>
//               {children}
//             </div>
//             <Footer />
//           </div>
//         </div>
//       </body>
//     </html>
//   );
// }


// import { Inter } from "next/font/google";
// import "./globals.css";
// import MiniDrawer from "./components/Sidebar";
// import Footer from "./components/Footer";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "MetaForge Pro - Professional Meta Tag Generator Suite",
//   description: "Generate professional Open Graph and Twitter Card meta tags with MetaForge Pro. 17+ generators for all social media platforms - fast, accurate, and free.",
//   // keywords: "meta tags generator, open graph, twitter cards, social media optimization, SEO tools, MetaForge",
//   // viewport: "width=device-width, initial-scale=1",
//   // robots: "index, follow",
//   // author: "MetaForge Team",
//   // themeColor: "#667eea",
//   // // FIXED: Proper favicon and icon references
//   // icons: {
//   //   icon: [
//   //     { url: "/favicon.ico", sizes: "any" }, // Main favicon - should be .ico format
//   //     { url: "/metaicon.png", sizes: "16x16", type: "image/png" },
//   //     { url: "/metaicon.png", sizes: "32x32", type: "image/png" },
//   //     { url: "/metaicon.png", sizes: "192x192", type: "image/png" }, // For PWA
//   //   ],
//   //   apple: [
//   //     { url: "/metaicon.png", sizes: "180x180", type: "image/png" },
//   //   ],
//   //   shortcut: "/favicon.ico", // Add shortcut icon
//   // },
//   // manifest: "/site.webmanifest",
//   // // Open Graph meta tags for MetaForge itself
//   // openGraph: {
//   //   title: "MetaForge Pro - Professional Meta Tag Generator Suite",
//   //   description: "Generate professional Open Graph and Twitter Card meta tags with ease. 17+ generators covering all major social media platforms.",
//   //   url: "https://metaforge.allaboutcse.com",
//   //   siteName: "MetaForge Pro",
//   //   images: [
//   //     {
//   //       url: "/og-image.png",
//   //       width: 1200,
//   //       height: 630,
//   //       alt: "MetaForge Pro - Meta Tag Generator Suite",
//   //     },
//   //   ],
//   //   locale: "en_US",
//   //   type: "website",
//   // },
//   // // Twitter Card meta tags for MetaForge itself
//   // twitter: {
//   //   card: "summary_large_image",
//   //   title: "MetaForge Pro - Professional Meta Tag Generator Suite",
//   //   description: "Generate professional Open Graph and Twitter Card meta tags with ease. Free, fast, and accurate.",
//   //   images: ["/twitter-image.png"],
//   //   creator: "@metaforge",
//   //   site: "@metaforge",
//   // },
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <head>
//         {/* ADDED: Manual favicon links for better browser support */}
//         <link rel="icon" href="/favicon.ico" sizes="any" />
//         <link rel="icon" href="/metaicon.png" type="image/png" />
//         <link rel="apple-touch-icon" href="/metaicon.png" />
        
//         {/* Additional head elements for MetaForge branding */}
//         <link rel="preconnect" href="https://fonts.googleapis.com" />
//         <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
//         <meta name="application-name" content="MetaForge Pro" />
//         <meta name="msapplication-TileColor" content="#667eea" />
//         <meta name="msapplication-config" content="/browserconfig.xml" />
//       </head>
//       <body 
//         className={inter.className} 
//         style={{ 
//           backgroundColor: "black", 
//           margin: 0, 
//           padding: 0,
//           fontFamily: inter.style.fontFamily 
//         }}
//       >
//         <div style={{ display: "flex", minHeight: "100vh" }}>
//           <MiniDrawer />
//           <div 
//             style={{ 
//               flexGrow: 1,
//               marginTop: "64px",
//               minHeight: "100vh",
//               display: "flex",
//               flexDirection: "column",
//               width: "100%",
//             }}
//           >
//             <div style={{ flexGrow: 1 }}>
//               {children}
//             </div>
//             <Footer />
//           </div>
//         </div>
//       </body>
//     </html>
//   );
// }


import { Inter } from "next/font/google";
import "./globals.css";
import MiniDrawer from "./components/Sidebar";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MetaForge Pro - Professional Meta Tag Generator Suite",
  description: "Generate professional Open Graph and Twitter Card meta tags with MetaForge Pro. 17+ generators for all social media platforms - fast, accurate, and free.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Favicon links for better browser support */}
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <link rel="icon" href="/metaicon.png" type="image/png" />
        <link rel="apple-touch-icon" href="/metaicon.png" />
        
        {/* Font optimization */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        
        {/* App metadata */}
        <meta name="application-name" content="MetaForge Pro" />
        <meta name="theme-color" content="#667eea" />
      </head>
      <body 
        className={inter.className} 
        style={{ 
          backgroundColor: "black", 
          margin: 0, 
          padding: 0,
          fontFamily: inter.style.fontFamily 
        }}
      >
        <div style={{ display: "flex", minHeight: "100vh" }}>
          <MiniDrawer />
          <div 
            style={{ 
              flexGrow: 1,
              marginTop: "64px",
              minHeight: "100vh",
              display: "flex",
              flexDirection: "column",
              width: "100%",
            }}
          >
            <div style={{ flexGrow: 1 }}>
              {children}
            </div>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
